package template

var K8S_HACK_TEMPLATE = `#!/usr/bin/env bash

# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

MODULE="{{ .RepoURL }}"
ROOT_PACKAGE=$(dirname ${BASH_SOURCE})
SCRIPT_ROOT=$(dirname ${BASH_SOURCE})/..
CODEGEN_PKG="${SCRIPT_ROOT}/vendor/k8s.io/code-generator"

# generate the code with:
# --output-base    because this script should also be able to run inside the vendor dir of
#                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
#                  instead of the $GOPATH directly. For normal projects this can be dropped.
bash ${CODEGEN_PKG}/generate-groups.sh "deepcopy,client,informer,lister" \
  $MODULE/pkg/client \
  $MODULE/pkg/apis \
  {{ .Group | ToLower }}:{{ .Package }} \
  --output-base $ROOT_PACKAGE \
  --go-header-file $SCRIPT_ROOT/hack/boilerplate.go.txt

# This generates the package structure under hack with the correct imports
rsync -av --stats {{ .RepoURL }}/pkg ..
`

var BOILERPLATE_TEMPLATE = `/*
File generated by www.github.com/drekle/protoc-gen-k8s.
You may update this boilerplate at any time: hack/boilerplate.go.txt
*/`

var TOOLS_TEMPLATE = `
// +build tools

/*
Copyright 2019 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This package imports things required by build scripts, to force ` + "`" + `go mod` + "`" + ` to see them as dependencies
package tools

import _ "k8s.io/code-generator"`
